# Generated by Django 5.0.7 on 2025-02-17 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="register_model",
            new_name="register_user",
        ),
    ]
