# Generated by Django 5.0.7 on 2025-02-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_rename_register_model_register_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="register_emp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=254)),
                ("passw", models.CharField(max_length=40)),
                ("cpassw", models.CharField(max_length=40)),
            ],
        ),
    ]
