# Generated by Django 5.0.7 on 2025-02-17 09:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_job_category_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", ckeditor.fields.RichTextField(max_length=5000)),
                ("budget_salary", models.CharField(max_length=255)),
                (
                    "education_req",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "experience_req",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("job_type", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("jobtag", models.CharField(max_length=255)),
                ("deadline", models.CharField(max_length=255)),
                ("vacancies", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True, default="available", max_length=255, null=True
                    ),
                ),
                ("employer", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Job_Category",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
