# Generated by Django 5.0.7 on 2025-02-18 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_experience"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("college", models.CharField(max_length=255)),
                ("stream", models.CharField(max_length=255)),
                ("result", models.CharField(max_length=255)),
                ("startingperiod", models.DateField()),
                ("endingperiod", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.register_user",
                    ),
                ),
            ],
        ),
    ]
