# Generated by Django 5.0.7 on 2025-02-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_saved"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeBuilder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("summary", models.TextField()),
                ("skills", models.TextField()),
                ("experience", models.TextField()),
                ("education", models.TextField()),
            ],
        ),
    ]
