# Generated by Django 5.0.7 on 2025-02-20 10:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_resumebuilder"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumebuilder",
            name="projects",
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
