# Generated by Django 5.0.7 on 2025-02-20 10:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_resumebuilder_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumebuilder",
            name="certifications",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resumebuilder",
            name="education",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resumebuilder",
            name="experience",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resumebuilder",
            name="phone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="resumebuilder",
            name="projects",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resumebuilder",
            name="skills",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resumebuilder",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
