# Generated by Django 5.0.7 on 2025-02-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_resumebuilder_certifications_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resumebuilder",
            name="certifications",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resumebuilder",
            name="projects",
            field=models.TextField(blank=True, null=True),
        ),
    ]
